CREATE DATABASE customer_shopping;
USE customer_shopping;

-- =====================================================
-- SQL Exploratory Data Analysis (EDA)
-- =====================================================

-- View Dataset
SELECT * 
FROM customer_sales;

-- Total Rows Count
SELECT 
	COUNT(*) as total_records
FROM customer_sales;

-- Check missing values in important columns

SELECT
    SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END) AS null_customer_id,
    SUM(CASE WHEN age IS NULL THEN 1 ELSE 0 END) AS null_age,
    SUM(CASE WHEN gender IS NULL THEN 1 ELSE 0 END) AS null_gender,
    SUM(CASE WHEN item_purchased IS NULL THEN 1 ELSE 0 END) AS null_item_purchased,
    SUM(CASE WHEN category IS NULL THEN 1 ELSE 0 END) AS null_category,
    SUM(CASE WHEN purchase_amount IS NULL THEN 1 ELSE 0 END) AS null_purchase_amount,
    SUM(CASE WHEN location IS NULL THEN 1 ELSE 0 END) AS null_location,
    SUM(CASE WHEN size IS NULL THEN 1 ELSE 0 END) AS null_size,
    SUM(CASE WHEN color IS NULL THEN 1 ELSE 0 END) AS null_color,
    SUM(CASE WHEN season IS NULL THEN 1 ELSE 0 END) AS null_season,
    SUM(CASE WHEN review_rating IS NULL THEN 1 ELSE 0 END) AS null_review_rating,
    SUM(CASE WHEN subscription_status IS NULL THEN 1 ELSE 0 END) AS null_subscription_status,
    SUM(CASE WHEN shipping_type IS NULL THEN 1 ELSE 0 END) AS null_shipping_type,
    SUM(CASE WHEN discount_applied IS NULL THEN 1 ELSE 0 END) AS null_discount_applied,
    SUM(CASE WHEN previous_purchases IS NULL THEN 1 ELSE 0 END) AS null_previous_purchases,
    SUM(CASE WHEN payment_method IS NULL THEN 1 ELSE 0 END) AS null_payment_method,
    SUM(CASE WHEN frequency_of_purchases IS NULL THEN 1 ELSE 0 END) AS null_frequency_of_purchases
FROM customer_sales;

-- Check Duplicate Customer IDs
SELECT 
    customer_id,
    COUNT(*) AS total_count
FROM customer_sales
GROUP BY customer_id
HAVING COUNT(*) > 1;

-- Unique Categories
SELECT DISTINCT category
FROM customer_sales;

-- Unique Payment Method
SELECT DISTINCT payment_method
FROM customer_sales;

-- =====================================================
-- Business Insights Questions
-- =====================================================

-- 1. Which category generates the highest revenue?

SELECT 
    category,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_sales
GROUP BY category
ORDER BY total_revenue DESC;

-- Business Problem :-
-- Company does not know which category contributes the most revenue.

-- Impact :-
-- Helps prioritize high-performing categories
-- Optimizes inventory planning
-- Improves marketing ROI

-- =====================================================

-- 2. Are discounts increasing purchase value?

SELECT
    discount_applied,
    ROUND(SUM(purchase_amount), 2) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer_sales
GROUP BY discount_applied
ORDER BY total_revenue DESC;

-- Business Problem :-
-- Discounts may reduce profits without increasing sales value.

-- Impact :-
-- Measures discount effectiveness
-- Helps reduce unnecessary discounts
-- Improves pricing strategy

-- 3. What is the total revenue generated by male and female customers?

SELECT 
    gender,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_sales
GROUP BY gender
ORDER BY total_revenue DESC;

-- Business Problem :-
-- Lack of visibility into revenue contribution by gender segments.

-- Impact :-
-- Supports targeted marketing campaigns
-- Improves customer segmentation
-- Enhances personalization efforts

-- =====================================================

-- 4. Which customers used discounts but still spent more than the average purchase amount?

SELECT 
    customer_id,
    purchase_amount
FROM customer_sales
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM customer_sales
);

-- Business Problem :-
-- Company cannot identify high-spending discount-sensitive customers.

-- Impact :-
-- Helps target premium customers
-- Improves retention campaigns
-- Supports strategic discount offers

-- 5. Top 5 products with the highest average review ratings

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_ratings
FROM customer_sales
GROUP BY item_purchased
ORDER BY avg_ratings DESC
LIMIT 5;

-- Bottom 5 products with the lowest average review ratings

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_ratings
FROM customer_sales
GROUP BY item_purchased
ORDER BY avg_ratings ASC
LIMIT 5;

-- Business Problem :-
-- Lack of visibility into product satisfaction levels.

-- Impact :-
-- Promotes highly rated products
-- Identifies weak-performing products
-- Improves customer experience

-- =====================================================

-- 6. Compare average purchase between Standard and Express shipping

SELECT 
    shipping_type,
    COUNT(*) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_sales
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY total_revenue DESC;

-- Business Problem :-
-- Company does not know if faster shipping influences spending.

-- Impact :-
-- Optimizes shipping strategies
-- Encourages premium shipping usage
-- Increases average order value

-- 7. Do subscribed customers spend more?

SELECT 
    subscription_status,
    COUNT(*) AS total_orders,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_sales
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Business Problem :-
-- Subscription program effectiveness is unclear.

-- Impact :-
-- Evaluates loyalty programs
-- Improves customer retention
-- Increases customer lifetime value

-- 8. Top 5 products with the highest discount usage percentage

SELECT 
    item_purchased,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discount_count,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*), 2
    ) AS discount_usage_pct
FROM customer_sales
GROUP BY item_purchased
ORDER BY discount_usage_pct DESC
LIMIT 5;

-- Business Problem :-
-- Some products may be overly dependent on discounts.

-- Impact :-
-- Helps optimize pricing strategy
-- Reduces profit margin loss
-- Identifies discount-driven products

-- =====================================================

-- 9. Segment customers into New, Returning, and Loyal customers

WITH customer_segments AS (
    SELECT 
        CASE 
            WHEN previous_purchases = 0 THEN 'New Customer'
            WHEN previous_purchases BETWEEN 1 AND 15 THEN 'Returning Customer'
            ELSE 'Loyal Customer'
        END AS customer_segment
    FROM customer_sales
)
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM customer_segments
GROUP BY customer_segment
ORDER BY customer_count DESC;

-- Business Problem :-
-- Lack of customer segmentation results in generic marketing strategies.

-- Impact :-
-- Enables personalized campaigns
-- Improves retention strategies
-- Increases customer engagement

-- =====================================================

-- 10. Top 3 most purchased products within each category

WITH top_products AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS ranks
    FROM customer_sales
    GROUP BY category, item_purchased
)

SELECT 
    category,
    item_purchased,
    total_purchases,
    ranks
FROM top_products
WHERE ranks <= 3
ORDER BY category, ranks, total_purchases DESC;

-- Business Problem :-
-- Company does not know top-performing products within categories.

-- Impact :-
-- Improves inventory optimization
-- Supports recommendation systems
-- Increases sales through best-selling products

-- =====================================================

-- 11. Are repeat buyers also more likely to subscribe?

-- 11. Are repeat buyers also more likely to subscribe?
SELECT
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyers'
        ELSE 'Normal Buyers'
    END AS customer_type,
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(
        (COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (
            PARTITION BY CASE WHEN previous_purchases > 5 THEN 'Repeat Buyers' ELSE 'Normal Buyers' END
        )), 2
    ) AS customer_percentage
FROM customer_sales
GROUP BY 1, 2
ORDER BY customer_type, customer_count DESC;

-- Business Problem :-
-- Relationship between repeat buying and subscriptions is unclear.

-- Impact :-
-- Improves subscription targeting
-- Supports loyalty strategies
-- Increases customer retention

-- =====================================================

-- 12. What is the revenue contribution of each age group?

SELECT
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
    END AS age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_sales
GROUP BY 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '51+'
    END
ORDER BY total_revenue DESC;

-- =====================================================
-- Final Conclusion
-- =====================================================

-- This SQL analysis project explored customer purchasing behavior,
-- revenue trends, customer segmentation, discount usage,
-- subscription patterns, and product performance.

-- Key business insights were extracted using:
-- Aggregate Functions
-- GROUP BY
-- CASE Statements
-- Common Table Expressions (CTEs)
-- Window Functions
-- Subqueries

-- The analysis helped identify:
-- High-revenue product categories
-- Customer spending patterns
-- Discount-driven products
-- Loyal and repeat customer behavior
-- Revenue contribution across demographics

-- This project demonstrates practical SQL skills for:
-- Data exploration
-- Business analysis
-- Customer segmentation
-- Revenue analysis
-- Decision-making support

-- End of analyis
-- =====================================================

-- Business Problem :-
-- Company lacks visibility into revenue contribution across age groups.

-- Impact :-
-- Enables age-based targeting
-- Improves marketing efficiency
-- Supports customer demographic analysis
